export interface SearchItem {
  title: string
  description: string
  href: string
  category: 'Component' | 'Documentation' | 'Token' | 'Theme'
  keywords?: string[]
}

export const searchData: SearchItem[] = [
  // Documentation Pages
  {
    title: 'Getting Started',
    description: 'Installation and setup guide for RTL Design System',
    href: '/getting-started',
    category: 'Documentation',
    keywords: ['install', 'setup', 'configuration', 'start'],
  },
  {
    title: 'Installation',
    description: 'Install RTL Design System in your project',
    href: '/documentation/installation',
    category: 'Documentation',
    keywords: ['npm', 'yarn', 'pnpm', 'install'],
  },
  {
    title: 'Quick Start',
    description: 'Build your first component in minutes',
    href: '/documentation/quick-start',
    category: 'Documentation',
    keywords: ['quick', 'start', 'tutorial', 'guide'],
  },
  {
    title: 'Configuration',
    description: 'Configure Tailwind and providers',
    href: '/documentation/configuration',
    category: 'Documentation',
    keywords: ['config', 'tailwind', 'providers', 'setup'],
  },
  {
    title: 'Props Documentation',
    description: 'Component props and API reference',
    href: '/documentation/props',
    category: 'Documentation',
    keywords: ['props', 'api', 'reference', 'interface'],
  },
  {
    title: 'Examples',
    description: 'Real-world usage examples',
    href: '/documentation/examples',
    category: 'Documentation',
    keywords: ['examples', 'patterns', 'usage'],
  },
  {
    title: 'RTL Guidelines',
    description: 'RTL-first development best practices',
    href: '/documentation/rtl',
    category: 'Documentation',
    keywords: ['rtl', 'right-to-left', 'arabic', 'hebrew', 'logical'],
  },
  {
    title: 'Bidirectional Text',
    description: 'Handling mixed-direction content',
    href: '/documentation/bidi',
    category: 'Documentation',
    keywords: ['bidi', 'bidirectional', 'mixed', 'direction'],
  },
  {
    title: 'Arabic Typography',
    description: 'Arabic font and text rendering guidelines',
    href: '/documentation/arabic',
    category: 'Documentation',
    keywords: ['arabic', 'typography', 'fonts', 'text'],
  },
  {
    title: 'WCAG Compliance',
    description: 'Web accessibility standards',
    href: '/documentation/wcag',
    category: 'Documentation',
    keywords: ['accessibility', 'wcag', 'a11y', 'compliance'],
  },
  {
    title: 'Keyboard Navigation',
    description: 'Keyboard accessibility guide',
    href: '/documentation/keyboard',
    category: 'Documentation',
    keywords: ['keyboard', 'navigation', 'shortcuts', 'accessibility'],
  },
  {
    title: 'Screen Readers',
    description: 'Screen reader optimization',
    href: '/documentation/screen-readers',
    category: 'Documentation',
    keywords: ['screen reader', 'nvda', 'jaws', 'voiceover', 'aria'],
  },
  {
    title: 'RTL Guide',
    description: 'Comprehensive RTL development guide',
    href: '/rtl-guide',
    category: 'Documentation',
    keywords: ['rtl', 'guide', 'tutorial'],
  },

  // Components
  {
    title: 'Button',
    description: 'Interactive button component with variants',
    href: '/components/button',
    category: 'Component',
    keywords: ['button', 'click', 'action', 'cta'],
  },
  {
    title: 'Card',
    description: 'Container for grouping content',
    href: '/components/card',
    category: 'Component',
    keywords: ['card', 'container', 'box'],
  },
  {
    title: 'Input',
    description: 'Text input field component',
    href: '/components/input',
    category: 'Component',
    keywords: ['input', 'text', 'field', 'form'],
  },
  {
    title: 'Label',
    description: 'Form label component',
    href: '/components/label',
    category: 'Component',
    keywords: ['label', 'form', 'text'],
  },
  {
    title: 'Badge',
    description: 'Small status indicator component',
    href: '/components/badge',
    category: 'Component',
    keywords: ['badge', 'tag', 'pill', 'status'],
  },
  {
    title: 'Separator',
    description: 'Visual divider component',
    href: '/components/separator',
    category: 'Component',
    keywords: ['separator', 'divider', 'line', 'hr'],
  },
  {
    title: 'Checkbox',
    description: 'Checkbox input component',
    href: '/components/checkbox',
    category: 'Component',
    keywords: ['checkbox', 'check', 'toggle', 'form'],
  },
  {
    title: 'Radio Group',
    description: 'Radio button group component',
    href: '/components/radio-group',
    category: 'Component',
    keywords: ['radio', 'option', 'choice', 'form'],
  },
  {
    title: 'Select',
    description: 'Dropdown selection component',
    href: '/components/select',
    category: 'Component',
    keywords: ['select', 'dropdown', 'picker', 'form'],
  },
  {
    title: 'Switch',
    description: 'Toggle switch component',
    href: '/components/switch',
    category: 'Component',
    keywords: ['switch', 'toggle', 'on-off'],
  },
  {
    title: 'Slider',
    description: 'Range slider component',
    href: '/components/slider',
    category: 'Component',
    keywords: ['slider', 'range', 'input'],
  },
  {
    title: 'Textarea',
    description: 'Multi-line text input',
    href: '/components/textarea',
    category: 'Component',
    keywords: ['textarea', 'text', 'multiline', 'form'],
  },
  {
    title: 'Alert',
    description: 'Alert message component',
    href: '/components/alert',
    category: 'Component',
    keywords: ['alert', 'message', 'notification', 'warning'],
  },
  {
    title: 'Toast',
    description: 'Temporary notification component',
    href: '/components/toast',
    category: 'Component',
    keywords: ['toast', 'notification', 'snackbar', 'message'],
  },
  {
    title: 'Dialog',
    description: 'Modal dialog component',
    href: '/components/dialog',
    category: 'Component',
    keywords: ['dialog', 'modal', 'popup', 'overlay'],
  },
  {
    title: 'Tooltip',
    description: 'Hover tooltip component',
    href: '/components/tooltip',
    category: 'Component',
    keywords: ['tooltip', 'hint', 'help', 'popover'],
  },
  {
    title: 'Progress',
    description: 'Progress bar component',
    href: '/components/progress',
    category: 'Component',
    keywords: ['progress', 'loading', 'bar', 'status'],
  },
  {
    title: 'Tabs',
    description: 'Tabbed navigation component',
    href: '/components/tabs',
    category: 'Component',
    keywords: ['tabs', 'navigation', 'panels'],
  },
  {
    title: 'Breadcrumb',
    description: 'Breadcrumb navigation component',
    href: '/components/breadcrumb',
    category: 'Component',
    keywords: ['breadcrumb', 'navigation', 'path'],
  },
  {
    title: 'Pagination',
    description: 'Page navigation component',
    href: '/components/pagination',
    category: 'Component',
    keywords: ['pagination', 'pages', 'navigation'],
  },
  {
    title: 'Sheet',
    description: 'Side sheet/drawer component',
    href: '/components/sheet',
    category: 'Component',
    keywords: ['sheet', 'drawer', 'sidebar', 'panel'],
  },
  {
    title: 'Accordion',
    description: 'Collapsible content component',
    href: '/components/accordion',
    category: 'Component',
    keywords: ['accordion', 'collapse', 'expand', 'faq'],
  },
  {
    title: 'Popover',
    description: 'Popover overlay component',
    href: '/components/popover',
    category: 'Component',
    keywords: ['popover', 'overlay', 'popup'],
  },
  {
    title: 'Avatar',
    description: 'User avatar component',
    href: '/components/avatar',
    category: 'Component',
    keywords: ['avatar', 'profile', 'image', 'user'],
  },

  // Other Pages
  {
    title: 'Design Tokens',
    description: 'Design system tokens and variables',
    href: '/tokens',
    category: 'Token',
    keywords: ['tokens', 'colors', 'spacing', 'typography', 'variables'],
  },
  {
    title: 'Themes',
    description: 'Available theme options',
    href: '/themes',
    category: 'Theme',
    keywords: ['themes', 'dark', 'light', 'minimal', 'futuristic'],
  },
  {
    title: 'Components Overview',
    description: 'Browse all available components',
    href: '/components',
    category: 'Component',
    keywords: ['components', 'ui', 'library'],
  },
]
