export interface SearchItem {
  title: string
  description: string
  href: string
  category: 'Component' | 'Documentation' | 'Token' | 'Theme' | 'Example'
  keywords?: string[]
}

export const searchData: SearchItem[] = [
  // Documentation Pages
  {
    title: 'Getting Started',
    description: 'Installation and setup guide for Noor UI',
    href: '/getting-started',
    category: 'Documentation',
    keywords: ['install', 'setup', 'configuration', 'start', 'noor'],
  },
  {
    title: 'Installation',
    description: 'Install Noor UI in your project',
    href: '/documentation/installation',
    category: 'Documentation',
    keywords: ['npm', 'yarn', 'pnpm', 'install', 'noor'],
  },
  {
    title: 'Quick Start',
    description: 'Build your first component in minutes',
    href: '/documentation/quick-start',
    category: 'Documentation',
    keywords: ['quick', 'start', 'tutorial', 'guide'],
  },
  {
    title: 'Configuration',
    description: 'Configure Tailwind and providers',
    href: '/documentation/configuration',
    category: 'Documentation',
    keywords: ['config', 'tailwind', 'providers', 'setup'],
  },
  {
    title: 'Props Documentation',
    description: 'Component props and API reference',
    href: '/documentation/props',
    category: 'Documentation',
    keywords: ['props', 'api', 'reference', 'interface'],
  },
  {
    title: 'Examples',
    description: 'Real-world usage examples',
    href: '/documentation/examples',
    category: 'Documentation',
    keywords: ['examples', 'patterns', 'usage'],
  },
  {
    title: 'RTL Guidelines',
    description: 'RTL-first development best practices',
    href: '/documentation/rtl',
    category: 'Documentation',
    keywords: ['rtl', 'right-to-left', 'arabic', 'hebrew', 'logical'],
  },
  {
    title: 'Bidirectional Text',
    description: 'Handling mixed-direction content',
    href: '/documentation/bidi',
    category: 'Documentation',
    keywords: ['bidi', 'bidirectional', 'mixed', 'direction'],
  },
  {
    title: 'Arabic Typography',
    description: 'Arabic font and text rendering guidelines',
    href: '/documentation/arabic',
    category: 'Documentation',
    keywords: ['arabic', 'typography', 'fonts', 'text'],
  },
  {
    title: 'WCAG Compliance',
    description: 'Web accessibility standards',
    href: '/documentation/wcag',
    category: 'Documentation',
    keywords: ['accessibility', 'wcag', 'a11y', 'compliance'],
  },
  {
    title: 'Keyboard Navigation',
    description: 'Keyboard accessibility guide',
    href: '/documentation/keyboard',
    category: 'Documentation',
    keywords: ['keyboard', 'navigation', 'shortcuts', 'accessibility'],
  },
  {
    title: 'Screen Readers',
    description: 'Screen reader optimization',
    href: '/documentation/screen-readers',
    category: 'Documentation',
    keywords: ['screen reader', 'nvda', 'jaws', 'voiceover', 'aria'],
  },
  {
    title: 'RTL Guide',
    description: 'Comprehensive RTL development guide',
    href: '/rtl-guide',
    category: 'Documentation',
    keywords: ['rtl', 'guide', 'tutorial'],
  },
  {
    title: 'Roadmap',
    description: 'Development roadmap and future plans',
    href: '/roadmap',
    category: 'Documentation',
    keywords: ['roadmap', 'plans', 'future', 'phases', 'timeline'],
  },
  {
    title: 'Utilities & Hooks',
    description: 'Helper functions and hooks for RTL-first development',
    href: '/utilities',
    category: 'Documentation',
    keywords: ['utilities', 'hooks', 'helpers', 'rtl', 'swipe', 'animation', 'gesture'],
  },
  {
    title: 'useSwipeDirection',
    description: 'RTL-aware swipe directions and animation values for gesture interactions',
    href: '/utilities#use-swipe-direction',
    category: 'Documentation',
    keywords: ['hook', 'swipe', 'direction', 'rtl', 'gesture', 'carousel', 'touch', 'mirror'],
  },
  {
    title: 'useRTLAnimation',
    description: 'Framer Motion animation variants that auto-adjust for RTL layouts',
    href: '/utilities#use-rtl-animation',
    category: 'Documentation',
    keywords: ['hook', 'animation', 'framer motion', 'rtl', 'slide', 'fade', 'carousel', 'variants'],
  },
  {
    title: 'useRelativeTime',
    description: 'Format dates as relative time strings with auto-updates and multilingual support',
    href: '/utilities#use-relative-time',
    category: 'Documentation',
    keywords: ['hook', 'time', 'date', 'relative', 'ago', 'locale', 'arabic', 'format'],
  },

  // Components
  {
    title: 'Button',
    description: 'Interactive button component with variants',
    href: '/components/button',
    category: 'Component',
    keywords: ['button', 'click', 'action', 'cta'],
  },
  {
    title: 'Card',
    description: 'Container for grouping content',
    href: '/components/card',
    category: 'Component',
    keywords: ['card', 'container', 'box'],
  },
  {
    title: 'FeatureCard',
    description: 'Feature showcase card with icon, title, and description',
    href: '/components/feature-card',
    category: 'Component',
    keywords: ['feature', 'card', 'showcase', 'icon', 'landing', 'marketing'],
  },
  {
    title: 'Input',
    description: 'Text input field component',
    href: '/components/input',
    category: 'Component',
    keywords: ['input', 'text', 'field', 'form'],
  },
  {
    title: 'Label',
    description: 'Form label component',
    href: '/components/label',
    category: 'Component',
    keywords: ['label', 'form', 'text'],
  },
  {
    title: 'Badge',
    description: 'Small status indicator component',
    href: '/components/badge',
    category: 'Component',
    keywords: ['badge', 'tag', 'pill', 'status'],
  },
  {
    title: 'Separator',
    description: 'Visual divider component',
    href: '/components/separator',
    category: 'Component',
    keywords: ['separator', 'divider', 'line', 'hr'],
  },
  {
    title: 'Form',
    description: 'Form state management with validation',
    href: '/components/form',
    category: 'Component',
    keywords: ['form', 'validation', 'input', 'submit', 'field', 'error', 'state'],
  },
  {
    title: 'Checkbox',
    description: 'Checkbox input component',
    href: '/components/checkbox',
    category: 'Component',
    keywords: ['checkbox', 'check', 'toggle', 'form'],
  },
  {
    title: 'Radio Group',
    description: 'Radio button group component',
    href: '/components/radio-group',
    category: 'Component',
    keywords: ['radio', 'option', 'choice', 'form'],
  },
  {
    title: 'Select',
    description: 'Dropdown selection component',
    href: '/components/select',
    category: 'Component',
    keywords: ['select', 'dropdown', 'picker', 'form'],
  },
  {
    title: 'Switch',
    description: 'Toggle switch component',
    href: '/components/switch',
    category: 'Component',
    keywords: ['switch', 'toggle', 'on-off'],
  },
  {
    title: 'Slider',
    description: 'Range slider component',
    href: '/components/slider',
    category: 'Component',
    keywords: ['slider', 'range', 'input'],
  },
  {
    title: 'Textarea',
    description: 'Multi-line text input',
    href: '/components/textarea',
    category: 'Component',
    keywords: ['textarea', 'text', 'multiline', 'form'],
  },
  {
    title: 'Rich Text Editor',
    description: 'WYSIWYG editor with formatting, headings, lists, and full RTL support',
    href: '/components/rich-text-editor',
    category: 'Component',
    keywords: ['editor', 'rich text', 'wysiwyg', 'tiptap', 'formatting', 'bold', 'italic', 'markdown', 'rtl', 'arabic', 'content', 'blog', 'cms'],
  },
  {
    title: 'File Upload',
    description: 'Drag-and-drop file upload with validation, previews, and accessibility',
    href: '/components/file-upload',
    category: 'Component',
    keywords: ['upload', 'file', 'drag', 'drop', 'image', 'upload', 'validation', 'form', 'attachment', 'preview'],
  },
  {
    title: 'User Menu',
    description: 'Dropdown menu with user avatar, profile info, and action items',
    href: '/components/user-menu',
    category: 'Component',
    keywords: ['user', 'menu', 'avatar', 'profile', 'dropdown', 'account', 'logout', 'settings', 'header'],
  },
  {
    title: 'Notification Center',
    description: 'Bell icon with notifications dropdown, unread count, and actions',
    href: '/components/notification-center',
    category: 'Component',
    keywords: ['notification', 'bell', 'alert', 'dropdown', 'popover', 'unread', 'badge', 'activity', 'feed', 'updates'],
  },
  {
    title: 'Dashboard Shell',
    description: 'Complete dashboard layout with sidebar navigation, header, and RTL support',
    href: '/components/dashboard-shell',
    category: 'Component',
    keywords: ['dashboard', 'layout', 'sidebar', 'navigation', 'header', 'shell', 'admin', 'panel', 'app', 'bilingual', 'responsive', 'mobile'],
  },
  {
    title: 'Alert',
    description: 'Alert message component',
    href: '/components/alert',
    category: 'Component',
    keywords: ['alert', 'message', 'notification', 'warning'],
  },
  {
    title: 'Toast',
    description: 'Temporary notification component',
    href: '/components/toast',
    category: 'Component',
    keywords: ['toast', 'notification', 'snackbar', 'message'],
  },
  {
    title: 'Dialog',
    description: 'Modal dialog component',
    href: '/components/dialog',
    category: 'Component',
    keywords: ['dialog', 'modal', 'popup', 'overlay'],
  },
  {
    title: 'Tooltip',
    description: 'Hover tooltip component',
    href: '/components/tooltip',
    category: 'Component',
    keywords: ['tooltip', 'hint', 'help', 'popover'],
  },
  {
    title: 'Progress',
    description: 'Progress bar component',
    href: '/components/progress',
    category: 'Component',
    keywords: ['progress', 'loading', 'bar', 'status'],
  },
  {
    title: 'Skeleton',
    description: 'Loading placeholder component',
    href: '/components/skeleton',
    category: 'Component',
    keywords: ['skeleton', 'loading', 'placeholder', 'shimmer', 'lazy'],
  },
  {
    title: 'Tabs',
    description: 'Tabbed navigation component',
    href: '/components/tabs',
    category: 'Component',
    keywords: ['tabs', 'navigation', 'panels'],
  },
  {
    title: 'Breadcrumb',
    description: 'Breadcrumb navigation component',
    href: '/components/breadcrumb',
    category: 'Component',
    keywords: ['breadcrumb', 'navigation', 'path'],
  },
  {
    title: 'Pagination',
    description: 'Page navigation component',
    href: '/components/pagination',
    category: 'Component',
    keywords: ['pagination', 'pages', 'navigation'],
  },
  {
    title: 'Sheet',
    description: 'Side sheet/drawer component',
    href: '/components/sheet',
    category: 'Component',
    keywords: ['sheet', 'drawer', 'sidebar', 'panel'],
  },
  {
    title: 'Accordion',
    description: 'Collapsible content component',
    href: '/components/accordion',
    category: 'Component',
    keywords: ['accordion', 'collapse', 'expand', 'faq'],
  },
  {
    title: 'Popover',
    description: 'Popover overlay component',
    href: '/components/popover',
    category: 'Component',
    keywords: ['popover', 'overlay', 'popup'],
  },
  {
    title: 'Avatar',
    description: 'User avatar component',
    href: '/components/avatar',
    category: 'Component',
    keywords: ['avatar', 'profile', 'image', 'user'],
  },
  {
    title: 'Table',
    description: 'Data table with mobile-responsive layout',
    href: '/components/table',
    category: 'Component',
    keywords: ['table', 'data', 'grid', 'rows', 'columns', 'mobile'],
  },
  {
    title: 'DataTable',
    description: 'Advanced data table with sorting, filtering, and pagination',
    href: '/components/data-table',
    category: 'Component',
    keywords: ['datatable', 'table', 'data', 'sorting', 'filter', 'pagination', 'search', 'grid', 'rows', 'columns', 'advanced'],
  },
  {
    title: 'Command',
    description: 'Command palette / search interface',
    href: '/components/command',
    category: 'Component',
    keywords: ['command', 'search', 'palette', 'finder'],
  },
  {
    title: 'Dropdown Menu',
    description: 'Dropdown menu with RTL support',
    href: '/components/dropdown-menu',
    category: 'Component',
    keywords: ['dropdown', 'menu', 'actions', 'options', 'rtl'],
  },
  {
    title: 'Context Menu',
    description: 'Right-click context menu',
    href: '/components/context-menu',
    category: 'Component',
    keywords: ['context', 'menu', 'right-click', 'actions', 'rtl'],
  },
  {
    title: 'Collapsible',
    description: 'Collapsible content sections',
    href: '/components/collapsible',
    category: 'Component',
    keywords: ['collapsible', 'collapse', 'expand', 'toggle', 'accordion'],
  },
  {
    title: 'Prayer Times',
    description: 'Beautiful prayer times display for Islamic applications',
    href: '/components/prayer-times',
    category: 'Component',
    keywords: ['prayer', 'times', 'salah', 'islamic', 'gcc', 'muslim', 'adhan', 'mosque', 'fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
  },
  {
    title: 'Hijri Date',
    description: 'Display Gregorian and Hijri (Islamic calendar) dates together',
    href: '/components/hijri-date',
    category: 'Component',
    keywords: ['hijri', 'islamic', 'calendar', 'date', 'gcc', 'muslim', 'lunar', 'gregorian', 'dual', 'bilingual'],
  },
  {
    title: 'Arabic Number',
    description: 'Utilities for Arabic-Indic numerals and SAR currency formatting',
    href: '/components/arabic-number',
    category: 'Component',
    keywords: ['arabic', 'number', 'numerals', 'indic', 'currency', 'sar', 'riyal', 'gcc', 'format', 'percentage', 'money', 'price'],
  },
  {
    title: 'Zakat Calculator',
    description: 'Calculate Islamic Zakat obligations on wealth and assets',
    href: '/components/zakat-calculator',
    category: 'Component',
    keywords: ['zakat', 'calculator', 'islamic', 'charity', 'wealth', 'nisab', 'gcc', 'muslim', 'finance', 'obligation', 'gold', 'silver', 'calculator'],
  },
  {
    title: 'Calendar',
    description: 'Date picker with Hijri calendar support, events, and range selection',
    href: '/components/calendar',
    category: 'Component',
    keywords: ['calendar', 'date', 'picker', 'hijri', 'islamic', 'gregorian', 'dual', 'range', 'events', 'gcc', 'month', 'selection'],
  },

  {
    title: 'Chart',
    description: 'Unified charting component with line, bar, area, and donut variants. RTL-aware with Arabic numeral formatting.',
    href: '/components/chart',
    category: 'Component',
    keywords: ['chart', 'graph', 'line', 'bar', 'area', 'donut', 'recharts', 'visualization', 'data', 'rtl', 'dashboard', 'analytics', 'kpi'],
  },

  {
    title: 'Timeline',
    description: 'Vertical event timeline with connecting lines, status-based styling, custom icons, and alternating layout. RTL-aware via logical properties.',
    href: '/components/timeline',
    category: 'Component',
    keywords: ['timeline', 'events', 'history', 'activity', 'log', 'status', 'progress', 'steps', 'chronological', 'vertical', 'alternating'],
  },

  {
    title: 'Blockquote',
    description: 'Styled quote component with accent, subtle variants and author attribution',
    href: '/components/blockquote',
    category: 'Component',
    keywords: ['blockquote', 'quote', 'citation', 'author', 'pull quote'],
  },
  {
    title: 'ButtonArrow',
    description: 'Button with directional arrow that auto-mirrors in RTL',
    href: '/components/button-arrow',
    category: 'Component',
    keywords: ['button', 'arrow', 'forward', 'back', 'external', 'rtl', 'direction'],
  },
  {
    title: 'Callout',
    description: 'Alert-style callout with info, warning, error, success, and note types',
    href: '/components/callout',
    category: 'Component',
    keywords: ['callout', 'alert', 'info', 'warning', 'error', 'success', 'note', 'tip'],
  },
  {
    title: 'Chat Message',
    description: 'Chat bubble component for AI and messaging interfaces',
    href: '/components/chat-message',
    category: 'Component',
    keywords: ['chat', 'message', 'bubble', 'ai', 'conversation', 'llm'],
  },
  {
    title: 'Content Renderer',
    description: 'Markdown/HTML content renderer with automatic RTL detection',
    href: '/components/content-renderer',
    category: 'Component',
    keywords: ['content', 'renderer', 'markdown', 'html', 'prose', 'rtl', 'auto'],
  },
  {
    title: 'Conversation History',
    description: 'Chat conversation history list for AI interfaces',
    href: '/components/conversation-history',
    category: 'Component',
    keywords: ['conversation', 'history', 'chat', 'ai', 'list', 'sessions'],
  },
  {
    title: 'Date Picker',
    description: 'Date picker with calendar popup and Hijri support',
    href: '/components/date-picker',
    category: 'Component',
    keywords: ['date', 'picker', 'calendar', 'hijri', 'input', 'form'],
  },
  {
    title: 'Empty State',
    description: 'Placeholder for empty content areas with icon and action',
    href: '/components/empty-state',
    category: 'Component',
    keywords: ['empty', 'state', 'placeholder', 'no data', 'no results'],
  },
  {
    title: 'Kbd',
    description: 'Keyboard shortcut display with platform-aware symbols',
    href: '/components/kbd',
    category: 'Component',
    keywords: ['keyboard', 'shortcut', 'kbd', 'key', 'command', 'hotkey'],
  },
  {
    title: 'Listing Card',
    description: 'Product or item listing card with image and details',
    href: '/components/listing-card',
    category: 'Component',
    keywords: ['listing', 'card', 'product', 'item', 'grid', 'marketplace'],
  },
  {
    title: 'Message Actions',
    description: 'Action buttons for AI chat messages (copy, regenerate, etc.)',
    href: '/components/message-actions',
    category: 'Component',
    keywords: ['message', 'actions', 'copy', 'regenerate', 'ai', 'chat', 'toolbar'],
  },
  {
    title: 'Model Selector',
    description: 'AI model selection dropdown for LLM interfaces',
    href: '/components/model-selector',
    category: 'Component',
    keywords: ['model', 'selector', 'ai', 'llm', 'gpt', 'claude', 'dropdown'],
  },
  {
    title: 'Number Input',
    description: 'Numeric input with increment/decrement controls',
    href: '/components/number-input',
    category: 'Component',
    keywords: ['number', 'input', 'numeric', 'increment', 'decrement', 'stepper'],
  },
  {
    title: 'Parameter Slider',
    description: 'Labeled slider for AI model parameters (temperature, etc.)',
    href: '/components/parameter-slider',
    category: 'Component',
    keywords: ['parameter', 'slider', 'ai', 'temperature', 'settings', 'range'],
  },
  {
    title: 'Prompt Input',
    description: 'Multi-line input for AI chat prompts with send button',
    href: '/components/prompt-input',
    category: 'Component',
    keywords: ['prompt', 'input', 'ai', 'chat', 'send', 'textarea', 'message'],
  },
  {
    title: 'Pull Quote',
    description: 'Large emphasized quote for highlighting key text',
    href: '/components/pull-quote',
    category: 'Component',
    keywords: ['pull', 'quote', 'emphasis', 'highlight', 'typography', 'blockquote'],
  },
  {
    title: 'Range Slider',
    description: 'Dual-handle slider for selecting a range of values',
    href: '/components/range-slider',
    category: 'Component',
    keywords: ['range', 'slider', 'dual', 'min', 'max', 'filter', 'price'],
  },
  {
    title: 'Reaction Picker',
    description: 'Emoji reaction picker for social features',
    href: '/components/reaction-picker',
    category: 'Component',
    keywords: ['reaction', 'emoji', 'like', 'social', 'picker', 'feedback'],
  },
  {
    title: 'Stats Card',
    description: 'Dashboard statistics card with value, trend, and icon',
    href: '/components/stats-card',
    category: 'Component',
    keywords: ['stats', 'card', 'dashboard', 'metric', 'kpi', 'trend', 'analytics'],
  },
  {
    title: 'Stepper',
    description: 'Multi-step progress indicator for forms and wizards',
    href: '/components/stepper',
    category: 'Component',
    keywords: ['stepper', 'steps', 'wizard', 'progress', 'multi-step', 'form'],
  },
  {
    title: 'Thinking Indicator',
    description: 'Animated typing/thinking indicator for AI interfaces',
    href: '/components/thinking-indicator',
    category: 'Component',
    keywords: ['thinking', 'typing', 'indicator', 'loading', 'ai', 'dots', 'animation'],
  },
  {
    title: 'Time Picker',
    description: 'Time selection input with hour/minute controls',
    href: '/components/time-picker',
    category: 'Component',
    keywords: ['time', 'picker', 'hour', 'minute', 'clock', 'input', 'form'],
  },
  {
    title: 'Token Counter',
    description: 'Token usage display for AI/LLM interfaces',
    href: '/components/token-counter',
    category: 'Component',
    keywords: ['token', 'counter', 'usage', 'ai', 'llm', 'limit', 'cost'],
  },
  {
    title: 'User Badge',
    description: 'Role and status badge with variants for author, moderator, admin',
    href: '/components/user-badge',
    category: 'Component',
    keywords: ['user', 'badge', 'role', 'status', 'author', 'moderator', 'admin', 'verified'],
  },
  {
    title: 'Workflow Canvas',
    description: 'Visual workflow editor canvas with nodes and connections',
    href: '/components/workflow-canvas',
    category: 'Component',
    keywords: ['workflow', 'canvas', 'node', 'editor', 'flow', 'diagram', 'visual'],
  },
  {
    title: 'Workflow Node',
    description: 'Individual node component for workflow diagrams',
    href: '/components/workflow-node',
    category: 'Component',
    keywords: ['workflow', 'node', 'block', 'step', 'action', 'trigger'],
  },

  // Examples
  {
    title: 'GCC Community Dashboard',
    description: 'Complete showcase of all GCC components in a real-world dashboard',
    href: '/examples/gcc-dashboard',
    category: 'Example',
    keywords: ['gcc', 'dashboard', 'prayer', 'zakat', 'hijri', 'arabic', 'islamic', 'example', 'showcase', 'demo'],
  },
  {
    title: 'Islamic Finance Dashboard',
    description: 'Comprehensive Islamic finance management with Zakat calculator, investment tracking, and transaction history',
    href: '/examples/islamic-finance-dashboard',
    category: 'Example',
    keywords: ['islamic', 'finance', 'zakat', 'investment', 'portfolio', 'transaction', 'hijri', 'prayer', 'halal', 'shariah', 'datatable', 'gcc', 'dashboard'],
  },
  {
    title: 'DataTable Showcase',
    description: 'Advanced data table with sorting, filtering, pagination, and export functionality',
    href: '/examples/datatable-showcase',
    category: 'Example',
    keywords: ['datatable', 'table', 'sorting', 'filtering', 'pagination', 'export', 'csv', 'search', 'data', 'grid'],
  },
  {
    title: 'Examples',
    description: 'Real-world usage examples and demos',
    href: '/examples',
    category: 'Example',
    keywords: ['examples', 'demos', 'templates', 'patterns', 'showcase'],
  },
  {
    title: 'Registration Form',
    description: 'Multi-step registration form with validation',
    href: '/examples/registration',
    category: 'Example',
    keywords: ['registration', 'form', 'multi-step', 'validation', 'signup', 'bilingual'],
  },
  {
    title: 'Dashboard',
    description: 'Analytics dashboard with charts and statistics',
    href: '/examples/dashboard',
    category: 'Example',
    keywords: ['dashboard', 'analytics', 'charts', 'stats', 'metrics', 'data', 'visualization'],
  },
  {
    title: 'E-commerce Product Page',
    description: 'Product page with gallery, reviews, and cart',
    href: '/examples/ecommerce',
    category: 'Example',
    keywords: ['ecommerce', 'product', 'shopping', 'cart', 'reviews', 'store', 'shop'],
  },
  {
    title: 'AI Agent Evaluations',
    description: 'OpenTelemetry-based evaluation dashboard for bilingual AI agents with Shariah compliance tracking',
    href: '/examples/ai-agent-evals',
    category: 'Example',
    keywords: ['ai', 'agent', 'evaluation', 'testing', 'opentelemetry', 'otel', 'metrics', 'performance', 'bilingual', 'gcc', 'islamic', 'shariah', 'compliance', 'llm', 'dashboard', 'monitoring', 'ecommerce'],
  },
  {
    title: 'Calendar Example',
    description: 'Interactive calendar demo with Hijri support and event markers',
    href: '/examples/calendar',
    category: 'Example',
    keywords: ['calendar', 'hijri', 'events', 'date', 'demo'],
  },
  {
    title: 'Accessible Inputs',
    description: 'Form inputs showcase with full accessibility compliance',
    href: '/examples/accessible-inputs',
    category: 'Example',
    keywords: ['accessible', 'inputs', 'form', 'a11y', 'wcag', 'aria'],
  },
  {
    title: 'AI Chat',
    description: 'Simple AI chat interface with streaming responses',
    href: '/examples/ai-chat-simple',
    category: 'Example',
    keywords: ['ai', 'chat', 'simple', 'conversation', 'llm', 'streaming'],
  },
  {
    title: 'AI Code Assistant',
    description: 'Code assistant interface with syntax highlighting and chat',
    href: '/examples/ai-code-assistant',
    category: 'Example',
    keywords: ['ai', 'code', 'assistant', 'programming', 'syntax', 'copilot'],
  },
  {
    title: 'AI Document QA',
    description: 'Document question-answering AI interface',
    href: '/examples/ai-document-qa',
    category: 'Example',
    keywords: ['ai', 'document', 'qa', 'question', 'answer', 'rag', 'retrieval'],
  },
  {
    title: 'AI Multi-Agent',
    description: 'Multi-agent AI workflow with coordinated tasks',
    href: '/examples/ai-multi-agent',
    category: 'Example',
    keywords: ['ai', 'multi', 'agent', 'workflow', 'orchestration', 'tasks'],
  },
  {
    title: 'AI Playground',
    description: 'Interactive playground for testing AI model parameters',
    href: '/examples/ai-playground',
    category: 'Example',
    keywords: ['ai', 'playground', 'model', 'parameters', 'temperature', 'testing'],
  },
  {
    title: 'AI Workflow',
    description: 'Visual AI workflow builder with node-based editor',
    href: '/examples/ai-workflow',
    category: 'Example',
    keywords: ['ai', 'workflow', 'builder', 'nodes', 'visual', 'editor', 'pipeline'],
  },
  {
    title: 'Blog Dashboard',
    description: 'Blog content management dashboard with posts, analytics, and editor',
    href: '/examples/blog-dashboard',
    category: 'Example',
    keywords: ['blog', 'dashboard', 'cms', 'content', 'posts', 'editor', 'analytics'],
  },
  {
    title: 'CMS Dashboard',
    description: 'Content management system with pages, media, and settings',
    href: '/examples/cms',
    category: 'Example',
    keywords: ['cms', 'content', 'management', 'pages', 'media', 'admin'],
  },
  {
    title: 'Marketplace',
    description: 'E-commerce marketplace with product listings, cart, and vendor pages',
    href: '/examples/marketplace',
    category: 'Example',
    keywords: ['marketplace', 'ecommerce', 'products', 'cart', 'vendor', 'shop'],
  },
  {
    title: 'B2B Marketplace',
    description: 'Business-to-business marketplace with RFQ and bulk ordering',
    href: '/examples/b2b-marketplace',
    category: 'Example',
    keywords: ['b2b', 'marketplace', 'rfq', 'bulk', 'wholesale', 'business'],
  },
  {
    title: 'Portfolio',
    description: 'Personal portfolio website with project showcase',
    href: '/examples/portfolio',
    category: 'Example',
    keywords: ['portfolio', 'personal', 'projects', 'showcase', 'resume'],
  },
  {
    title: 'Real Estate',
    description: 'Real estate listing platform with property details and search',
    href: '/examples/real-estate',
    category: 'Example',
    keywords: ['real estate', 'property', 'listing', 'search', 'housing'],
  },
  {
    title: 'Workflow Builder',
    description: 'Basic workflow builder with drag-and-drop node editor',
    href: '/examples/workflow-basic',
    category: 'Example',
    keywords: ['workflow', 'builder', 'nodes', 'drag', 'drop', 'editor', 'visual'],
  },
  {
    title: 'Healthcare Clinic',
    description: 'Multi-page healthcare clinic management with patients, appointments, and prescriptions',
    href: '/examples/healthcare',
    category: 'Example',
    keywords: ['healthcare', 'clinic', 'patients', 'appointments', 'prescriptions', 'medical', 'doctor'],
  },
  {
    title: 'Education School',
    description: 'School management system with students, teachers, grades, and attendance',
    href: '/examples/education',
    category: 'Example',
    keywords: ['education', 'school', 'students', 'teachers', 'grades', 'attendance', 'assignments'],
  },

  // Other Pages
  {
    title: 'Documentation',
    description: 'Guides for installation, RTL, accessibility, and more',
    href: '/documentation',
    category: 'Documentation',
    keywords: ['documentation', 'docs', 'guides', 'reference'],
  },
  {
    title: 'Starters',
    description: 'Ready-made project templates to jumpstart your app',
    href: '/starters',
    category: 'Documentation',
    keywords: ['starters', 'templates', 'boilerplate', 'quickstart', 'kitab', 'blog'],
  },
  {
    title: 'License',
    description: 'Noor UI license information',
    href: '/license',
    category: 'Documentation',
    keywords: ['license', 'mit', 'open source', 'terms'],
  },
  {
    title: 'Design Tokens',
    description: 'Design system tokens and variables',
    href: '/tokens',
    category: 'Token',
    keywords: ['tokens', 'colors', 'spacing', 'typography', 'variables'],
  },
  {
    title: 'Themes',
    description: 'Available theme options',
    href: '/themes',
    category: 'Theme',
    keywords: ['themes', 'dark', 'light', 'minimal', 'futuristic'],
  },
  {
    title: 'Components Overview',
    description: 'Browse all available components',
    href: '/components',
    category: 'Component',
    keywords: ['components', 'ui', 'library'],
  },
]
