export interface SearchItem {
  title: string
  description: string
  href: string
  category: 'Component' | 'Documentation' | 'Token' | 'Theme' | 'Example'
  keywords?: string[]
}

export const searchData: SearchItem[] = [
  // Documentation Pages
  {
    title: 'Getting Started',
    description: 'Installation and setup guide for RTL Design System',
    href: '/getting-started',
    category: 'Documentation',
    keywords: ['install', 'setup', 'configuration', 'start'],
  },
  {
    title: 'Installation',
    description: 'Install RTL Design System in your project',
    href: '/documentation/installation',
    category: 'Documentation',
    keywords: ['npm', 'yarn', 'pnpm', 'install'],
  },
  {
    title: 'Quick Start',
    description: 'Build your first component in minutes',
    href: '/documentation/quick-start',
    category: 'Documentation',
    keywords: ['quick', 'start', 'tutorial', 'guide'],
  },
  {
    title: 'Configuration',
    description: 'Configure Tailwind and providers',
    href: '/documentation/configuration',
    category: 'Documentation',
    keywords: ['config', 'tailwind', 'providers', 'setup'],
  },
  {
    title: 'Props Documentation',
    description: 'Component props and API reference',
    href: '/documentation/props',
    category: 'Documentation',
    keywords: ['props', 'api', 'reference', 'interface'],
  },
  {
    title: 'Examples',
    description: 'Real-world usage examples',
    href: '/documentation/examples',
    category: 'Documentation',
    keywords: ['examples', 'patterns', 'usage'],
  },
  {
    title: 'RTL Guidelines',
    description: 'RTL-first development best practices',
    href: '/documentation/rtl',
    category: 'Documentation',
    keywords: ['rtl', 'right-to-left', 'arabic', 'hebrew', 'logical'],
  },
  {
    title: 'Bidirectional Text',
    description: 'Handling mixed-direction content',
    href: '/documentation/bidi',
    category: 'Documentation',
    keywords: ['bidi', 'bidirectional', 'mixed', 'direction'],
  },
  {
    title: 'Arabic Typography',
    description: 'Arabic font and text rendering guidelines',
    href: '/documentation/arabic',
    category: 'Documentation',
    keywords: ['arabic', 'typography', 'fonts', 'text'],
  },
  {
    title: 'WCAG Compliance',
    description: 'Web accessibility standards',
    href: '/documentation/wcag',
    category: 'Documentation',
    keywords: ['accessibility', 'wcag', 'a11y', 'compliance'],
  },
  {
    title: 'Keyboard Navigation',
    description: 'Keyboard accessibility guide',
    href: '/documentation/keyboard',
    category: 'Documentation',
    keywords: ['keyboard', 'navigation', 'shortcuts', 'accessibility'],
  },
  {
    title: 'Screen Readers',
    description: 'Screen reader optimization',
    href: '/documentation/screen-readers',
    category: 'Documentation',
    keywords: ['screen reader', 'nvda', 'jaws', 'voiceover', 'aria'],
  },
  {
    title: 'RTL Guide',
    description: 'Comprehensive RTL development guide',
    href: '/rtl-guide',
    category: 'Documentation',
    keywords: ['rtl', 'guide', 'tutorial'],
  },

  // Components
  {
    title: 'Button',
    description: 'Interactive button component with variants',
    href: '/components/button',
    category: 'Component',
    keywords: ['button', 'click', 'action', 'cta'],
  },
  {
    title: 'Card',
    description: 'Container for grouping content',
    href: '/components/card',
    category: 'Component',
    keywords: ['card', 'container', 'box'],
  },
  {
    title: 'Input',
    description: 'Text input field component',
    href: '/components/input',
    category: 'Component',
    keywords: ['input', 'text', 'field', 'form'],
  },
  {
    title: 'Label',
    description: 'Form label component',
    href: '/components/label',
    category: 'Component',
    keywords: ['label', 'form', 'text'],
  },
  {
    title: 'Badge',
    description: 'Small status indicator component',
    href: '/components/badge',
    category: 'Component',
    keywords: ['badge', 'tag', 'pill', 'status'],
  },
  {
    title: 'Separator',
    description: 'Visual divider component',
    href: '/components/separator',
    category: 'Component',
    keywords: ['separator', 'divider', 'line', 'hr'],
  },
  {
    title: 'Form',
    description: 'Form state management with validation',
    href: '/components/form',
    category: 'Component',
    keywords: ['form', 'validation', 'input', 'submit', 'field', 'error', 'state'],
  },
  {
    title: 'Checkbox',
    description: 'Checkbox input component',
    href: '/components/checkbox',
    category: 'Component',
    keywords: ['checkbox', 'check', 'toggle', 'form'],
  },
  {
    title: 'Radio Group',
    description: 'Radio button group component',
    href: '/components/radio-group',
    category: 'Component',
    keywords: ['radio', 'option', 'choice', 'form'],
  },
  {
    title: 'Select',
    description: 'Dropdown selection component',
    href: '/components/select',
    category: 'Component',
    keywords: ['select', 'dropdown', 'picker', 'form'],
  },
  {
    title: 'Switch',
    description: 'Toggle switch component',
    href: '/components/switch',
    category: 'Component',
    keywords: ['switch', 'toggle', 'on-off'],
  },
  {
    title: 'Slider',
    description: 'Range slider component',
    href: '/components/slider',
    category: 'Component',
    keywords: ['slider', 'range', 'input'],
  },
  {
    title: 'Textarea',
    description: 'Multi-line text input',
    href: '/components/textarea',
    category: 'Component',
    keywords: ['textarea', 'text', 'multiline', 'form'],
  },
  {
    title: 'Alert',
    description: 'Alert message component',
    href: '/components/alert',
    category: 'Component',
    keywords: ['alert', 'message', 'notification', 'warning'],
  },
  {
    title: 'Toast',
    description: 'Temporary notification component',
    href: '/components/toast',
    category: 'Component',
    keywords: ['toast', 'notification', 'snackbar', 'message'],
  },
  {
    title: 'Dialog',
    description: 'Modal dialog component',
    href: '/components/dialog',
    category: 'Component',
    keywords: ['dialog', 'modal', 'popup', 'overlay'],
  },
  {
    title: 'Tooltip',
    description: 'Hover tooltip component',
    href: '/components/tooltip',
    category: 'Component',
    keywords: ['tooltip', 'hint', 'help', 'popover'],
  },
  {
    title: 'Progress',
    description: 'Progress bar component',
    href: '/components/progress',
    category: 'Component',
    keywords: ['progress', 'loading', 'bar', 'status'],
  },
  {
    title: 'Skeleton',
    description: 'Loading placeholder component',
    href: '/components/skeleton',
    category: 'Component',
    keywords: ['skeleton', 'loading', 'placeholder', 'shimmer', 'lazy'],
  },
  {
    title: 'Tabs',
    description: 'Tabbed navigation component',
    href: '/components/tabs',
    category: 'Component',
    keywords: ['tabs', 'navigation', 'panels'],
  },
  {
    title: 'Breadcrumb',
    description: 'Breadcrumb navigation component',
    href: '/components/breadcrumb',
    category: 'Component',
    keywords: ['breadcrumb', 'navigation', 'path'],
  },
  {
    title: 'Pagination',
    description: 'Page navigation component',
    href: '/components/pagination',
    category: 'Component',
    keywords: ['pagination', 'pages', 'navigation'],
  },
  {
    title: 'Sheet',
    description: 'Side sheet/drawer component',
    href: '/components/sheet',
    category: 'Component',
    keywords: ['sheet', 'drawer', 'sidebar', 'panel'],
  },
  {
    title: 'Accordion',
    description: 'Collapsible content component',
    href: '/components/accordion',
    category: 'Component',
    keywords: ['accordion', 'collapse', 'expand', 'faq'],
  },
  {
    title: 'Popover',
    description: 'Popover overlay component',
    href: '/components/popover',
    category: 'Component',
    keywords: ['popover', 'overlay', 'popup'],
  },
  {
    title: 'Avatar',
    description: 'User avatar component',
    href: '/components/avatar',
    category: 'Component',
    keywords: ['avatar', 'profile', 'image', 'user'],
  },
  {
    title: 'Table',
    description: 'Data table with mobile-responsive layout',
    href: '/components/table',
    category: 'Component',
    keywords: ['table', 'data', 'grid', 'rows', 'columns', 'mobile'],
  },
  {
    title: 'DataTable',
    description: 'Advanced data table with sorting, filtering, and pagination',
    href: '/components/data-table',
    category: 'Component',
    keywords: ['datatable', 'table', 'data', 'sorting', 'filter', 'pagination', 'search', 'grid', 'rows', 'columns', 'advanced'],
  },
  {
    title: 'Command',
    description: 'Command palette / search interface',
    href: '/components/command',
    category: 'Component',
    keywords: ['command', 'search', 'palette', 'finder'],
  },
  {
    title: 'Dropdown Menu',
    description: 'Dropdown menu with RTL support',
    href: '/components/dropdown-menu',
    category: 'Component',
    keywords: ['dropdown', 'menu', 'actions', 'options', 'rtl'],
  },
  {
    title: 'Context Menu',
    description: 'Right-click context menu',
    href: '/components/context-menu',
    category: 'Component',
    keywords: ['context', 'menu', 'right-click', 'actions', 'rtl'],
  },
  {
    title: 'Collapsible',
    description: 'Collapsible content sections',
    href: '/components/collapsible',
    category: 'Component',
    keywords: ['collapsible', 'collapse', 'expand', 'toggle', 'accordion'],
  },
  {
    title: 'Prayer Times',
    description: 'Beautiful prayer times display for Islamic applications',
    href: '/components/prayer-times',
    category: 'Component',
    keywords: ['prayer', 'times', 'salah', 'islamic', 'gcc', 'muslim', 'adhan', 'mosque', 'fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
  },
  {
    title: 'Hijri Date',
    description: 'Display Gregorian and Hijri (Islamic calendar) dates together',
    href: '/components/hijri-date',
    category: 'Component',
    keywords: ['hijri', 'islamic', 'calendar', 'date', 'gcc', 'muslim', 'lunar', 'gregorian', 'dual', 'bilingual'],
  },
  {
    title: 'Arabic Number',
    description: 'Utilities for Arabic-Indic numerals and SAR currency formatting',
    href: '/components/arabic-number',
    category: 'Component',
    keywords: ['arabic', 'number', 'numerals', 'indic', 'currency', 'sar', 'riyal', 'gcc', 'format', 'percentage', 'money', 'price'],
  },
  {
    title: 'Zakat Calculator',
    description: 'Calculate Islamic Zakat obligations on wealth and assets',
    href: '/components/zakat-calculator',
    category: 'Component',
    keywords: ['zakat', 'calculator', 'islamic', 'charity', 'wealth', 'nisab', 'gcc', 'muslim', 'finance', 'obligation', 'gold', 'silver', 'calculator'],
  },
  {
    title: 'Calendar',
    description: 'Date picker with Hijri calendar support, events, and range selection',
    href: '/components/calendar',
    category: 'Component',
    keywords: ['calendar', 'date', 'picker', 'hijri', 'islamic', 'gregorian', 'dual', 'range', 'events', 'gcc', 'month', 'selection'],
  },

  // Examples
  {
    title: 'GCC Community Dashboard',
    description: 'Complete showcase of all GCC components in a real-world dashboard',
    href: '/examples/gcc-dashboard',
    category: 'Example',
    keywords: ['gcc', 'dashboard', 'prayer', 'zakat', 'hijri', 'arabic', 'islamic', 'example', 'showcase', 'demo'],
  },
  {
    title: 'Examples',
    description: 'Real-world usage examples and demos',
    href: '/examples',
    category: 'Example',
    keywords: ['examples', 'demos', 'templates', 'patterns', 'showcase'],
  },
  {
    title: 'Registration Form',
    description: 'Multi-step registration form with validation',
    href: '/examples/registration',
    category: 'Example',
    keywords: ['registration', 'form', 'multi-step', 'validation', 'signup', 'bilingual'],
  },
  {
    title: 'Dashboard',
    description: 'Analytics dashboard with charts and statistics',
    href: '/examples/dashboard',
    category: 'Example',
    keywords: ['dashboard', 'analytics', 'charts', 'stats', 'metrics', 'data', 'visualization'],
  },
  {
    title: 'E-commerce Product Page',
    description: 'Product page with gallery, reviews, and cart',
    href: '/examples/ecommerce',
    category: 'Example',
    keywords: ['ecommerce', 'product', 'shopping', 'cart', 'reviews', 'store', 'shop'],
  },

  // Other Pages
  {
    title: 'Design Tokens',
    description: 'Design system tokens and variables',
    href: '/tokens',
    category: 'Token',
    keywords: ['tokens', 'colors', 'spacing', 'typography', 'variables'],
  },
  {
    title: 'Themes',
    description: 'Available theme options',
    href: '/themes',
    category: 'Theme',
    keywords: ['themes', 'dark', 'light', 'minimal', 'futuristic'],
  },
  {
    title: 'Components Overview',
    description: 'Browse all available components',
    href: '/components',
    category: 'Component',
    keywords: ['components', 'ui', 'library'],
  },
]
